### ISSUE TITLE
Excluding directories does not work

### ISSUE THREAD

**Issue by david-polak** [webpack-contrib/terser-webpack-plugin#31]
I can not exclude directories, I tried the usual regexes that work with webpack e.g. `/\/src/` or `/.*templates.*/` and or variations. Apart from `/*/` which should be equivalent to `/\/src/` none of what I tried seems to work. 

* Operating System: Linux
* Node Version: v11.2.0
* NPM Version: 6.4.1
* webpack Version: 4.25.1
* terser-webpack-plugin Version: 1.1.0

**Comment by evilebottnawi** [comment]
@david-polak because `exclude` option use `processed` assets (not sources). It is impossible exclude source modules.

**Comment by evilebottnawi** [comment]
@david-polak it is impossible. Why? Because webpack bundle your modules in chunks (`js` files) and when pass their through `minificator`. If you find bug in minimicator (i.e. `terser`) better to create issue in https://github.com/terser-js/terser. Why minification don't uses on modules - it is inefficient.

**Comment by nullromo** [comment]
I am running into the same issue. @evilebottnawi When I run webpack with minification turned off, my code works. When I run it with minification on, it doesn't. For this reason, I want to be able to turn off minification for only those modules which Terser breaks.

**Comment by evilebottnawi** [comment]
@nullromo You can't disable minification for modules, if you need it you can open an issue in terser repo about:
```
/*! terser-ignore-start */
// ... code
/*! terser-ignore-end */
```
